[package]
name = "life"
version = "0.1.0"
authors = ["Alexander Molchevsky <molchevsky@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
toml = "0.8.8"
